import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const SecureNotesApp());

class SecureNotesApp extends StatefulWidget { const SecureNotesApp({super.key}); @override State<SecureNotesApp> createState()=>_SecureNotesAppState(); }
class _SecureNotesAppState extends State<SecureNotesApp>{
  bool dark=false; @override void initState(){super.initState(); _load();}
  Future<void> _load() async{final p=await SharedPreferences.getInstance(); setState(()=>dark=p.getBool('dark')??false);} 
  Future<void> toggle(bool v) async{final p=await SharedPreferences.getInstance(); await p.setBool('dark',v); setState(()=>dark=v);} 
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Notlar',theme:AppTheme.light,darkTheme:AppTheme.dark,themeMode:dark?ThemeMode.dark:ThemeMode.light,home:PinScreen(onTheme:toggle,dark:dark));
}

class AppTheme{
  static const green=Color(0xff16c789), purple=Color(0xff6658f6);
  static ThemeData light=ThemeData(useMaterial3:true,brightness:Brightness.light,scaffoldBackgroundColor:const Color(0xfff8f8f7),colorScheme:ColorScheme.fromSeed(seedColor:purple,brightness:Brightness.light),cardTheme:CardThemeData(color:Colors.white,elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22),side:BorderSide(color:Colors.black.withOpacity(.06)))));
  static ThemeData dark=ThemeData(useMaterial3:true,brightness:Brightness.dark,scaffoldBackgroundColor:const Color(0xff090c10),colorScheme:ColorScheme.fromSeed(seedColor:purple,brightness:Brightness.dark),cardTheme:CardThemeData(color:const Color(0xff171b21),elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22),side:BorderSide(color:Colors.white.withOpacity(.07)))));
}

class Store{
  static Future<List<Map<String,dynamic>>> getList(String k) async{final p=await SharedPreferences.getInstance(); return (jsonDecode(p.getString(k)??'[]') as List).cast<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();}
  static Future<void> setList(String k,List<Map<String,dynamic>> v) async{final p=await SharedPreferences.getInstance(); await p.setString(k,jsonEncode(v));}
}

class PinScreen extends StatefulWidget{final Function(bool) onTheme; final bool dark; const PinScreen({super.key,required this.onTheme,required this.dark}); @override State<PinScreen> createState()=>_PinScreenState();}
class _PinScreenState extends State<PinScreen>{String pin='', saved=''; bool setup=false; @override void initState(){super.initState(); _l();} Future<void> _l() async{final p=await SharedPreferences.getInstance(); saved=p.getString('pin')??''; setup=saved.isEmpty; setState((){});} 
  void add(String n) async{ if(pin.length<6)setState(()=>pin+=n); if(pin.length>=4){ if(setup){final p=await SharedPreferences.getInstance(); await p.setString('pin',pin); open();} else if(pin==saved){open();} else {ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('PIN hatalı'))); setState(()=>pin='');}}}
  void open()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Home(onTheme:widget.onTheme,dark:widget.dark)));
  @override Widget build(BuildContext c)=>Scaffold(body:Container(decoration:BoxDecoration(gradient:LinearGradient(colors:Theme.of(c).brightness==Brightness.dark?[const Color(0xff090c10),const Color(0xff1b1237)]:[const Color(0xfffbf8ff),const Color(0xffeee8ff)],begin:Alignment.topCenter,end:Alignment.bottomCenter)),child:SafeArea(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.lock_rounded,size:70,color:AppTheme.purple),Text(setup?'Yeni PIN oluştur':'PIN giriniz',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w800)),const SizedBox(height:18),Text('●'*pin.length,style:const TextStyle(fontSize:34,letterSpacing:10)),const SizedBox(height:20),Wrap(spacing:18,runSpacing:18,alignment:WrapAlignment.center,children:[for(final n in ['1','2','3','4','5','6','7','8','9','←','0','✓']) ElevatedButton(style:ElevatedButton.styleFrom(shape:const CircleBorder(),fixedSize:const Size(72,72)),onPressed:(){if(n=='←'&&pin.isNotEmpty)setState(()=>pin=pin.substring(0,pin.length-1)); else if(n!='←'&&n!='✓')add(n);},child:Text(n,style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold))) ]),const SizedBox(height:35),const Text('makrosoft.NET',style:TextStyle(fontWeight:FontWeight.w800,color:AppTheme.purple))]))));}
}

class Home extends StatefulWidget{final Function(bool) onTheme; final bool dark; const Home({super.key,required this.onTheme,required this.dark}); @override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0; late bool dark; @override void initState(){super.initState(); dark=widget.dark;} @override Widget build(BuildContext c){final pages=[NotesPage(),RemindersPage(),PasswordsPage(),SettingsPage(dark:dark,onTheme:(v){setState(()=>dark=v); widget.onTheme(v);})]; return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.description_outlined),label:'NOTLAR'),NavigationDestination(icon:Icon(Icons.notifications_none),label:'HATIRLAT'),NavigationDestination(icon:Icon(Icons.lock_outline),label:'ŞİFRELER'),NavigationDestination(icon:Icon(Icons.settings_outlined),label:'AYARLAR')]),floatingActionButton: tab<3?FloatingActionButton(backgroundColor:AppTheme.purple,foregroundColor:Colors.white,onPressed:()=>addDialog(tab),child:const Icon(Icons.add,size:34)):null);}
  void addDialog(int t){ if(t==0) NoteEditor(onSave:()=>setState((){})).show(context); if(t==1) ReminderEditor(onSave:()=>setState((){})).show(context); if(t==2) PasswordEditor(onSave:()=>setState((){})).show(context); }
}

class PageShell extends StatelessWidget{final String title; final Widget child; const PageShell({super.key,required this.title,required this.child}); @override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.note_alt_outlined),const SizedBox(width:10),Text(title,style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900))]),const SizedBox(height:20),Container(padding:const EdgeInsets.symmetric(horizontal:18),decoration:BoxDecoration(color:Theme.of(c).cardColor,borderRadius:BorderRadius.circular(28)),child:const TextField(decoration:InputDecoration(icon:Icon(Icons.search),border:InputBorder.none,hintText:'Düşüncelerini ara...'))),const SizedBox(height:18),Expanded(child:child)]));}

class NotesPage extends StatefulWidget{const NotesPage({super.key}); @override State<NotesPage> createState()=>_NotesPageState();}
class _NotesPageState extends State<NotesPage>{List<Map<String,dynamic>> items=[]; @override void initState(){super.initState(); load();} Future<void> load() async{items=await Store.getList('notes'); setState((){});} @override Widget build(c)=>PageShell(title:'Notlar',child:ListView(children:[const Text('Notlarım',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),for(final e in items) AppCard(color:Color(e['color']??0xff16c789),child:ListTile(title:Text(e['title']??'',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(e['body']??''),trailing:PopupMenuButton(itemBuilder:(_)=>[const PopupMenuItem(value:'del',child:Text('Sil'))],onSelected:(_)async{items.remove(e); await Store.setList('notes',items); load();}))]));}
}
class NoteEditor{final VoidCallback onSave; NoteEditor({required this.onSave}); void show(BuildContext c){final t=TextEditingController(),b=TextEditingController(); showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>FormBox(title:'Not ekle',children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Başlık')),TextField(controller:b,decoration:const InputDecoration(labelText:'Not'),maxLines:3),SaveButton(onTap:()async{final l=await Store.getList('notes'); l.insert(0,{'title':t.text,'body':b.text,'color':0xff16c789}); await Store.setList('notes',l); Navigator.pop(c); onSave();})]));}}

class RemindersPage extends StatefulWidget{const RemindersPage({super.key}); @override State<RemindersPage> createState()=>_RemindersPageState();}
class _RemindersPageState extends State<RemindersPage>{List<Map<String,dynamic>> items=[]; @override void initState(){super.initState(); load();} Future<void> load() async{items=await Store.getList('reminders'); setState((){});} bool lateTask(e){final d=DateTime.tryParse(e['date']??''); return !(e['done']??false)&&d!=null&&d.isBefore(DateTime.now());} @override Widget build(c)=>PageShell(title:'Hatırlatmalar',child:ListView(children:[const Text('Görevlerim',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),for(final e in items) AppCard(color:lateTask(e)?Colors.red:AppTheme.green,child:ListTile(title:Text(e['title']??'',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${e['type']=='daily'?'Günlük tekrarlı':'Tarih bazlı'} • ${e['date']??''}'),leading:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:(e['done']??false)?Colors.green:(lateTask(e)?Colors.red:null),foregroundColor:Colors.white),onPressed:()async{e['done']=true; await Store.setList('reminders',items); load();},child:Icon((e['done']??false)?Icons.check:Icons.priority_high)),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{final ok=await confirm(c,'Bu hatırlatmayı silmek istediğinize emin misiniz?'); if(ok){items.remove(e); await Store.setList('reminders',items); load();}}))]));}}
class ReminderEditor{final VoidCallback onSave; ReminderEditor({required this.onSave}); void show(BuildContext c){final t=TextEditingController(); bool daily=true; DateTime d=DateTime.now(); showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>StatefulBuilder(builder:(c,set)=>FormBox(title:'Hatırlatma ekle',children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Görev adı')),SwitchListTile(title:Text(daily?'Günlük tekrarlı':'Tarih bazlı'),value:daily,onChanged:(v)=>set(()=>daily=v)),ListTile(title:Text(DateFormat('dd.MM.yyyy HH:mm').format(d)),trailing:const Icon(Icons.calendar_month),onTap:()async{final nd=await showDatePicker(context:c,firstDate:DateTime(2024),lastDate:DateTime(2035),initialDate:d); if(nd!=null)set(()=>d=DateTime(nd.year,nd.month,nd.day,d.hour,d.minute));}),SaveButton(onTap:()async{final l=await Store.getList('reminders'); l.insert(0,{'title':t.text,'type':daily?'daily':'date','date':d.toIso8601String(),'done':false}); await Store.setList('reminders',l); Navigator.pop(c); onSave();})])));}}

class PasswordsPage extends StatefulWidget{const PasswordsPage({super.key}); @override State<PasswordsPage> createState()=>_PasswordsPageState();}
class _PasswordsPageState extends State<PasswordsPage>{List<Map<String,dynamic>> items=[]; Set<int> show={}; @override void initState(){super.initState(); load();} Future<void> load() async{items=await Store.getList('passwords'); setState((){});} @override Widget build(c)=>PageShell(title:'Şifrelerim',child:ListView(children:[const Text('Kayıtlı Şifreler',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),for(int i=0;i<items.length;i++) AppCard(color:AppTheme.purple,child:ListTile(title:Text(items[i]['title']??'',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${items[i]['user']??''}\nŞifre: ${show.contains(i)?items[i]['pass']:'********'}'),isThreeLine:true,leading:IconButton(icon:Icon(show.contains(i)?Icons.visibility_off:Icons.visibility),onPressed:()=>setState(()=>show.contains(i)?show.remove(i):show.add(i))),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{final ok=await confirm(c,'Bu şifre kaydını silmek istediğinize emin misiniz?'); if(ok){items.removeAt(i); await Store.setList('passwords',items); load();}}))]));}}
class PasswordEditor{final VoidCallback onSave; PasswordEditor({required this.onSave}); void show(BuildContext c){final title=TextEditingController(),user=TextEditingController(),pass=TextEditingController(),web=TextEditingController(),note=TextEditingController(); showModalBottomSheet(context:c,isScrollControlled:true,builder:(_)=>FormBox(title:'Şifre kaydı ekle',children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Başlık / Platform')),TextField(controller:user,decoration:const InputDecoration(labelText:'Kullanıcı adı veya e-posta')),TextField(controller:pass,decoration:const InputDecoration(labelText:'Şifre')),TextField(controller:web,decoration:const InputDecoration(labelText:'Web sitesi')),TextField(controller:note,decoration:const InputDecoration(labelText:'Not')),SaveButton(onTap:()async{final l=await Store.getList('passwords'); l.insert(0,{'title':title.text,'user':user.text,'pass':pass.text,'web':web.text,'note':note.text}); await Store.setList('passwords',l); Navigator.pop(c); onSave();})]));}}

class SettingsPage extends StatelessWidget{final bool dark; final Function(bool) onTheme; const SettingsPage({super.key,required this.dark,required this.onTheme}); @override Widget build(c)=>PageShell(title:'Ayarlar',child:ListView(children:[AppCard(color:AppTheme.purple,child:SwitchListTile(title:const Text('Koyu / Açık Tema'),subtitle:const Text('Gözü yormayan tema seçimi'),value:dark,onChanged:onTheme)),const SizedBox(height:12),const Text('Yedekleme ve 256-bit şifreleme sonraki sürüme hazır modül olarak eklenebilir.') ]));}

class AppCard extends StatelessWidget{final Color color; final Widget child; const AppCard({super.key,required this.color,required this.child}); @override Widget build(c)=>Container(margin:const EdgeInsets.only(top:14),decoration:BoxDecoration(color:Theme.of(c).cardColor,borderRadius:BorderRadius.circular(18),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.06),blurRadius:16)],border:Border(left:BorderSide(color:color,width:5))),child:child);}
class FormBox extends StatelessWidget{final String title; final List<Widget> children; const FormBox({super.key,required this.title,required this.children}); @override Widget build(c)=>Padding(padding:EdgeInsets.only(left:22,right:22,top:22,bottom:MediaQuery.of(c).viewInsets.bottom+22),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),...children])));}
class SaveButton extends StatelessWidget{final VoidCallback onTap; const SaveButton({super.key,required this.onTap}); @override Widget build(c)=>Padding(padding:const EdgeInsets.only(top:16),child:SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:onTap,child:const Text('Kaydet'))));}
Future<bool> confirm(BuildContext c,String msg)async=> await showDialog<bool>(context:c,builder:(_)=>AlertDialog(title:const Text('Onay'),content:Text(msg),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('İptal')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Sil'))]))??false;
